### ISSUE TITLE
scan a string?

### ISSUE THREAD

**Issue by masterQian** [tearosccebe/fast_io#7]

**Comment by tearosccebe** [comment]
need to include<string> before include<fast_io.h>

**Comment by masterQian** [comment]
I mean how to use fast_ IO replaces the following code:

std::string str;

cin >> str;

Or:

char str[10];

scanf("%s",str);



Another problem is how to use fast_ IO replaces sprintf and sscanf. It seems that concat can't be seen in the latest version

**Comment by tearosccebe** [comment]
```cpp

std::string str;
scan(str);
```

**Comment by masterQian** [comment]
but..
In template: static_assert failed due to requirement 'not_scanable' "type not scannable. need context_scanable"

**Comment by tearosccebe** [comment]
> but.. In template: static_assert failed due to requirement 'not_scanable' "type not scannable. need context_scanable"
你这卢瑟没#include <string>在fast_io.h 前

**Comment by masterQian** [comment]
🥺🥺🥺🥺🥺
